name: Deploy Backend to Staging
on:
  push:
    branches:
      - staging/backend

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
            
      - name: Build Spring Boot application
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: "./build.sh"

      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: staging-deploy
          path: demo/build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: staging-deploy
      - name: Check if artifact is present
        run: |
          ls -R ./
          if [ -d demo/build ]; then
            echo "Artifact found"
          else
            echo "Artifact not found"
            exit 1
          fi
