name: Deploy Backend to Staging
on:
  push:
    branches:
      - staging/backend

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
            
      - name: Build Spring Boot application
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - run: "./build.sh"
